package v1

import "github.com/imyuliz/api-scheduler/pkg/runtime"

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Flow) DeepCopyInto(out *Flow) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	// TODO: sub field deep copy
	// in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	// in.Spec.DeepCopyInto(&out.Spec)
	// in.Status.DeepCopyInto(&out.Status)
	return
}

func (in *Flow) DeepCopy() *Flow {
	if in == nil {
		return nil
	}
	out := new(Flow)
	in.DeepCopyInto(out)
	return out
}

func (in *Flow) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
